import type { GuideLore } from "./types";

/** The Rune Guide's deeper content, English. From the user's NotebookLM research, in our own words. */
export const guideEn: GuideLore = {
  history: [
    {
      title: "What is the Elder Futhark?",
      paragraphs: [
        "The Elder Futhark is the oldest runic alphabet, used by the Germanic peoples of northern Europe from about AD 150 to 800. It is named after its first six letters: F, U, Th, A, R, K.",
        "From the 8th century it gave way to the 16-sign Younger Futhark in Scandinavia, and to the extended Anglo-Saxon Futhorc in Britain.",
        "Its 24 signs fall into three groups of eight. Each group is an aett (plural aettir), Old Norse for family or kin, named after its first rune or the god tied to it: the aett of Freyr and Freyja (starting with Fehu), of Heimdall (with Hagalaz) and of Týr (with Tiwaz).",
      ],
    },
    {
      title: "The oldest inscriptions",
      paragraphs: [
        "One of the oldest known rune inscriptions is the word \"harja\" on the Vimose comb from Denmark, dated to around AD 160.",
        "The oldest complete row of all 24 signs in order is on the Kylver stone on Gotland, Sweden (around AD 400). The order of the futhark we know today comes largely from rows like this.",
      ],
    },
    {
      title: "What were runes used for?",
      paragraphs: [
        "Runes are first of all a script. They were carved into wood, stone, bone and metal: on weapons, jewellery and memorial stones, as names, marks of ownership, dedications and short protective formulas such as alu and laukaz.",
        "The Roman historian Tacitus, writing his Germania in AD 98, describes Germanic tribes cutting marked slips from a fruit-bearing tree, scattering them on a white cloth and drawing lots. Whether those marks were runes is not known; it is disputed.",
        "Archaeology gives no direct evidence that runes were read by drawing stones as they are today. Rune reading is largely a modern reconstruction, and this app presents it as one.",
      ],
    },
    {
      title: "Modern rune reading",
      paragraphs: [
        "Esoteric interest in the runes began in the late 19th century and turned into today's practice of reading them in the second half of the 20th.",
        "The book that spread it around the world was Ralph Blum's The Book of Runes, published in 1982. Drawing partly on the structure of the I Ching, Blum gave each rune a meaning for reading.",
      ],
      modern: true,
    },
    {
      title: "The blank rune",
      paragraphs: [
        "The unmarked stone found in some sets has no place in the Elder Futhark or in Viking Age finds. It entered reading with Ralph Blum's book in 1982, when the spare blank stone packed with commercial sets was read as \"the unknown\".",
        "This app does not use a blank rune.",
      ],
      modern: true,
    },
    {
      title: "Reversed runes",
      paragraphs: [
        "Reading a rune that lands upside down with a different, usually shadowed meaning is modern too, borrowed from reversed cards in tarot. Old inscriptions know no such rule.",
        "Nine runes are symmetrical, look the same either way up and are read upright only: Gebo, Hagalaz, Nauthiz, Isa, Jera, Eihwaz, Sowilo, Ingwaz and Dagaz.",
      ],
      modern: true,
    },
    {
      title: "Before a reading",
      paragraphs: [
        "Modern readers begin with a small pause: a quiet place, a few deep breaths, and the question held clearly in mind. Some lay out a cloth and draw the stones onto it.",
        "The runes are not a prophecy but a mirror to think with. Whatever the stone says, the choice and the path are yours.",
      ],
      modern: true,
    },
  ],

  spreadsIntro:
    "A spread is the order in which the stones are drawn and what each place speaks of. All of today's spreads are modern; most spread with the rune books of the 20th century.",

  spreads: [
    {
      key: "single",
      title: "Single Rune",
      origin: "The simplest and most common form of modern rune reading; the \"rune of the day\" is one.",
      layout: "One stone is drawn from the bag.",
      positions: ["Answer: the heart of the matter, the day's main energy, or the point to focus on."],
      questions: "Daily direction, quick clarity, questions like \"What should I pay attention to today?\"",
      reading: "A single stone is not a verdict but a mirror: you think about the day in its light.",
    },
    {
      key: "three",
      title: "Past · Present · Future",
      origin: "A modern layout inspired by the three Norns who weave fate: Urd (what was), Verdandi (what is becoming) and Skuld (what shall be).",
      layout: "Three stones side by side, from left to right.",
      positions: [
        "Past: the influences and roots that prepared the present.",
        "Present: the situation, energy or challenge at work now.",
        "Future: where things are likely to lead if the course does not change.",
      ],
      questions: "Questions about where a process comes from and where it is going.",
      reading: "Read each stone on its own, then join them from left to right like a story of cause and effect.",
    },
    {
      key: "four",
      title: "Four-Rune Relationship Spread",
      origin: "A modern layout made for questions about relationships.",
      layout: "Four stones side by side.",
      positions: [
        "Your energy: the feeling, intention and outlook you bring.",
        "You: your stance and expectations in the relationship.",
        "The other: the feelings, intentions and attitude they bring.",
        "Outcome: the shared direction your meeting may lead to.",
      ],
      questions: "Couples, partnerships and questions of harmony.",
      reading: "The first two stones speak of you, the third of the other; the fourth shows where the two meet.",
    },
    {
      key: "five",
      title: "Five-Rune Cross",
      origin: "A cross layout developed in modern reading books.",
      layout: "One stone in the centre and four around it: left, top, right and bottom.",
      positions: [
        "Centre: the heart of the question and where things stand.",
        "Left (past): the causes that led here.",
        "Top (aim): the conscious goal, or a strength you can draw on.",
        "Right (obstacle): inner resistance, or what needs letting go.",
        "Bottom (outcome): the step to take and where it can lead.",
      ],
      questions: "Complex decisions and situations that need a deeper look.",
      reading: "The horizontal line, from the past through the centre to the obstacle, tells how things came to stand and what lies ahead; the vertical, from the aim down to the outcome, where they can lead; read where they cross, in the centre.",
    },
    {
      key: "scatter",
      title: "Free Scatter",
      origin: "The method closest to the lot-casting Tacitus describes; nine stones nod to the nine worlds of the myths. Not in the app, for interest.",
      layout: "Nine stones are taken from the bag and cast freely onto a cloth.",
      positions: [
        "Stones near the centre: the most pressing focus.",
        "Stones near the edges: secondary influences.",
        "Face-up stones speak of what is active, face-down ones of what is not yet seen.",
      ],
      questions: "A broad look at life, a view of the year ahead.",
      reading: "The stones are read in groups, by how close they fall to one another.",
    },
  ],

  runes: {
    Fehu: {
      proto: "*fehu",
      poem: "In the Old English poem wealth is a comfort to everyone, yet whoever hopes for honour must share it freely.",
      myth: "Linked to Freyr and Freyja, the gods of plenty, whose name the first aett bears.",
      inner: "Energy returning after exhaustion; seeing the worth of what you have.",
      shadow: "Greed; hoarding what should flow.",
      harmony: "Grows stronger with Uruz; shaken by the storm of Hagalaz.",
      question: "Am I sharing what I have in a balanced way?",
      talisman: "Often used in talismans for abundance and gain.",
    },
    Uruz: {
      proto: "*ūruz",
      poem: "In the poem the aurochs is a proud, wild strength that fights with its great horns.",
      myth: "Names the aurochs, Europe's extinct wild ox; modern readings tie it to nature's raw strength, some to Thor.",
      inner: "Endurance of body and mind; noticing your own strength.",
      shadow: "Uncontrolled anger; strength spent in the wrong place.",
      harmony: "Grows steadily with Fehu; strained by the limits of Nauthiz.",
      question: "Am I turning my strength to building rather than breaking?",
      talisman: "Used in talismans for endurance and resilience.",
    },
    Thurisaz: {
      proto: "*þurisaz",
      poem: "In the poems the thorn is sharp and painful to whoever grasps it; the giant is a destructive force.",
      myth: "Associated with the giants (jötnar) and with Mjölnir, the hammer of Thor who fought them.",
      inner: "Guarding your boundaries; a sudden awakening.",
      shadow: "Reacting too fast; picking needless fights.",
      harmony: "Completes protection with Algiz; clashes with the stillness of Isa.",
      question: "In guarding my boundaries, am I becoming a thorn that hurts those around me?",
      talisman: "Drawn for active protection against outside harm.",
    },
    Ansuz: {
      proto: "*ansuz",
      poem: "In the Old English poem it is the source of speech and wisdom; in the Icelandic one it is the old father of Asgard, Odin.",
      myth: "Its name means \"a god\"; directly tied to Odin, god of speech, poetry and wisdom.",
      inner: "Clarity of mind; finding what you want to say.",
      shadow: "Using words to mislead, or being misled by them.",
      harmony: "Kindles inspiration with Kenaz; feels cramped under Nauthiz.",
      question: "Do my words bring light, or confusion?",
      talisman: "Used in talismans for communication, exams and inspiration.",
    },
    Raidho: {
      proto: "*raidō",
      poem: "In the poem riding seems easy to the one sitting in the hall, and hard to the one setting out on a long road on a strong horse.",
      myth: "Tied to the journey and to ordered movement; modern readings see in it the rhythm of life.",
      inner: "Finding your own rhythm; setting out at the right time.",
      shadow: "Wandering without aim, or never settling.",
      harmony: "A good travelling companion to Ehwaz; brought to a halt by Isa.",
      question: "Is the rhythm of my life in my own hands right now?",
      talisman: "Used in talismans for safe travel.",
    },
    Kenaz: {
      proto: "*kaunan",
      poem: "In the Old English poem the torch is a bright fire that gives light and warmth to those in the hall.",
      myth: "Linked to the hearth fire and to craft: the controlled fire that turns raw matter into form.",
      inner: "An inner light waking; the wish to create.",
      shadow: "The fire running out of control into a scorching passion.",
      harmony: "Brings clarity with Sowilo; can be put out by the waters of Laguz.",
      question: "Can I turn the fire in my mind into making something?",
      talisman: "Used in talismans for creativity and learning.",
    },
    Gebo: {
      proto: "*gebō",
      poem: "In the Old English poem generosity brings honour to the giver and support to those in need.",
      myth: "Speaks of a world held together by gifts: the gift, the return, and the bond between them.",
      inner: "Balance between giving and receiving.",
      shadow: "One-sided dependence; keeping count of what was given.",
      harmony: "Brings happiness with Wunjo; turns into dependence with Nauthiz.",
      question: "Do I keep the balance of giving and receiving in my relationships?",
      talisman: "Used for commitment and fair partnership; the heart of the Bond Knot.",
    },
    Wunjo: {
      proto: "*wunjō",
      poem: "In the poem joy belongs to the one who knows little of pain and sorrow, and lives in plenty and peace.",
      myth: "Speaks of harmony within a community and of joy that is shared.",
      inner: "Inner contentment and well-being.",
      shadow: "Shallow optimism that looks away from real problems.",
      harmony: "Builds peace with Gebo; shaken by the storm of Hagalaz.",
      question: "Who am I sharing my joy with today?",
      talisman: "Used in talismans for peace and shared happiness.",
    },
    Hagalaz: {
      proto: "*hagalaz",
      poem: "In the poem hail is the whitest of grains, whirled from the sky and tossed by the wind, until it turns to water.",
      myth: "Speaks of the forces of nature no one controls; the second aett begins with it.",
      inner: "Waking through crisis; a clearing out.",
      shadow: "Resisting change and being buried under it.",
      harmony: "Builds endurance with Nauthiz; interrupts the joy of Wunjo for a while.",
      question: "What am I learning from the storms I cannot avoid?",
      talisman: "Used in talismans for breaking through blockages.",
    },
    Nauthiz: {
      proto: "*naudiz",
      poem: "In the poem need tightens the chest, yet if heeded in time it becomes help and rescue.",
      myth: "Modern readings tie it to the Norns who weave fate, and to fire kindled by friction.",
      inner: "Self-discipline; a time when the will is tested.",
      shadow: "Giving up into helplessness.",
      harmony: "Makes patient growth with Jera; stands against the plenty of Fehu.",
      question: "What strength are my difficulties teaching me?",
      talisman: "Used in talismans for will and endurance.",
    },
    Isa: {
      proto: "*īsaz",
      poem: "In the poem ice is very cold and slippery; it gleams like glass and makes a frozen floor.",
      myth: "Speaks of winter and stillness: the moment when everything stops moving.",
      inner: "Quieting the mind; looking inward.",
      shadow: "Withdrawing and freezing up inside.",
      harmony: "Waits with Jera for the thaw; at odds with the movement of Raidho.",
      question: "Where in my life do I need to stop and wait?",
      talisman: "Used to hold a situation still, or to gather focus.",
    },
    Jera: {
      proto: "*jēra",
      poem: "In the poem the year and its harvest give people hope: the earth returns what was worked.",
      myth: "Tied to the turning year and the harvest, and to Freyr, god of plenty.",
      inner: "Keeping to your natural rhythm; waiting for the fruit of your work.",
      shadow: "Impatience; wanting the result before its time.",
      harmony: "Crowns transformation with Dagaz; lives through a hard season with Hagalaz.",
      question: "Which seeds that I sowed am I harvesting now?",
      talisman: "Used in talismans for abundance and patient growth.",
    },
    Eihwaz: {
      proto: "*ī(h)waz",
      poem: "In the poem the yew is hard on the outside and deep in its roots, a keeper of fire.",
      myth: "The yew lives for centuries; modern readings link it to the world tree Yggdrasil and to the threshold between life and death.",
      inner: "Spiritual resilience; bending in the storm without breaking.",
      shadow: "Rigidity; refusing to bend at all.",
      harmony: "Makes a deep mystery with Perthro; stands up to the storm of Hagalaz.",
      question: "Can I bend before the storm and stay standing?",
      talisman: "Used in talismans for steadfast protection.",
    },
    Perthro: {
      proto: "*perþō",
      poem: "In the Old English poem it is a game that warriors play and laugh over in the hall.",
      myth: "The one rune whose meaning is not truly known; most readings link it to a dice cup, to chance and to the mystery of fate.",
      inner: "Listening to intuition; sensing what is hidden.",
      shadow: "Leaving everything to chance to avoid responsibility.",
      harmony: "Speaks of the depth of fate with Eihwaz; clashes with words twisted under Ansuz.",
      question: "How open am I to the surprises life may bring?",
      talisman: "Used in talismans for luck and intuition.",
    },
    Algiz: {
      proto: "*algiz",
      poem: "In the Old English poem it is a sedge growing in the marsh that cuts the hand that touches it.",
      myth: "Its name is linked to the elk; its upraised arms are read as a protecting shield.",
      inner: "Intuitive alertness; feeling safe.",
      shadow: "Seeing danger everywhere and living on guard.",
      harmony: "A strong armour with Sowilo; at odds with the recklessness of Thurisaz.",
      question: "Can I protect my own boundaries?",
      talisman: "The most common sign of protection; found in most protective talismans.",
    },
    Sowilo: {
      proto: "*sōwilō",
      poem: "In the poem the sun guides seafarers and gives joy and light to those on land.",
      myth: "The sun itself; in Norse tales linked to Sól, who carries the sun across the sky.",
      inner: "Vitality; wholeness and self-belief.",
      shadow: "An inflated ego that scorches everyone around.",
      harmony: "Leads to victory with Tiwaz; melts the ice of Isa.",
      question: "Does my light bring warmth to those around me?",
      talisman: "Used in talismans for success and energy.",
    },
    Tiwaz: {
      proto: "*tīwaz",
      poem: "In the Old English poem it is a guiding star that never strays above the night mists and keeps its faith.",
      myth: "Directly tied to Týr, god of justice and sacrifice; the third aett bears his name.",
      inner: "Unshakable will; standing behind what you know is right.",
      shadow: "Rigid rule-keeping; blind loyalty.",
      harmony: "Makes a balanced strength with Berkano; has no patience for twisted words.",
      question: "Am I fighting fairly for what I believe in?",
      talisman: "Used in talismans for courage, justice and victory.",
    },
    Berkano: {
      proto: "*berkanan",
      poem: "In the Old English poem the birch, though it bears no seed, puts out shoots; its branches are fair and its leaves reach the sky.",
      myth: "Linked to birth, to growth and to images of protective motherhood.",
      inner: "Renewal; nourishing yourself with care.",
      shadow: "Smothering others with too much protection.",
      harmony: "Grows in balance with Tiwaz; lives through a hard time with Hagalaz.",
      question: "What do I need to nourish for a fresh start?",
      talisman: "Used in talismans for new beginnings, family and renewal.",
    },
    Ehwaz: {
      proto: "*ehwaz",
      poem: "In the poem the horse is pride and joy to its rider, and a comfort to the restless.",
      myth: "Speaks of the trust between horse and rider: two beings travelling as one.",
      inner: "Body and mind in harmony.",
      shadow: "Trusting blindly and losing your own direction.",
      harmony: "Builds harmony in company with Mannaz; falls into mistrust with Nauthiz.",
      question: "How much trust do I inspire in my relationships?",
      talisman: "Used in talismans for mutual trust and cooperation.",
    },
    Mannaz: {
      proto: "*mannaz",
      poem: "In the Old English poem a person is dear to their kin, yet every person returns one day to the earth.",
      myth: "Speaks of the human being, of human community, and of knowing oneself.",
      inner: "Knowing yourself; accepting the limits of being human.",
      shadow: "Losing yourself in the crowd.",
      harmony: "Builds harmony with Ehwaz; can grow lonely in the crisis of Hagalaz.",
      question: "How well does my role among others fit who I am?",
      talisman: "Used in talismans for community support and self-awareness.",
    },
    Laguz: {
      proto: "*laguz",
      poem: "In the Old English poem water seems endless to those who venture out on a rolling ship, and the waves frighten them.",
      myth: "Speaks of water, flow and depth; modern readings tie it to the unconscious and to feeling.",
      inner: "Trusting your intuition; letting yourself flow.",
      shadow: "Drowning in feeling and losing all reason.",
      harmony: "Ripens from within with Ingwaz; can put out the fire of Kenaz.",
      question: "Am I listening to the voice of my intuition?",
      talisman: "Used in talismans for intuition and dreams.",
    },
    Ingwaz: {
      proto: "*ingwaz",
      poem: "In the Old English poem Ing was first seen among the East Danes, then went away over the waves with his wagon.",
      myth: "The rune of Ing, god of fertility (often taken as a name of Freyr); it speaks of the hidden strength inside a seed.",
      inner: "Gathering energy within; waiting to ripen.",
      shadow: "Keeping the seed inside forever and never sowing it.",
      harmony: "Brings new births with Berkano; patient within the waiting of Isa.",
      question: "What is waiting inside me to ripen?",
      talisman: "Used in talismans for completion and new beginnings.",
    },
    Dagaz: {
      proto: "*dagaz",
      poem: "In the Old English poem day is a precious light to all: hope and joy to rich and poor alike.",
      myth: "Speaks of dawn, where night meets day: the passage from darkness into light.",
      inner: "The darkness of the mind clearing; clarity.",
      shadow: "Dazzled by the speed of change, unable to keep up.",
      harmony: "Brings full light with Sowilo; at odds with the frozen stillness of Isa.",
      question: "Which dark corner of my life am I letting light into?",
      talisman: "Used in talismans for awakening and a new page.",
    },
    Othala: {
      proto: "*ōþala",
      poem: "In the Old English poem ancestral land is precious to anyone who can live at home in peace and plenty.",
      myth: "Speaks of inherited land, of what comes from the ancestors, and of belonging.",
      inner: "Honouring your roots; belonging somewhere.",
      shadow: "Living in the shadow of the past; closing up to change.",
      harmony: "Builds lasting prosperity with Fehu; tested at the roots by Hagalaz.",
      question: "Which value handed down to me still holds me up today?",
      talisman: "Used in talismans for home, family and property.",
    },
  },
};
