import type { GuideLore } from "./types";

/** Rune Rehberi derin içerik, Türkçe. Kaynak: kullanıcının NotebookLM araştırması; kendi cümlelerimizle. */
export const guideTr: GuideLore = {
  history: [
    {
      title: "Elder Futhark nedir?",
      paragraphs: [
        "Elder Futhark (Kadim Futhark), Kuzey Avrupa'nın Germen halklarının yaklaşık MS 150 ile 800 yılları arasında kullandığı en eski rune alfabesidir. Adını ilk altı harfinden alır: F, U, Th, A, R, K.",
        "8. yüzyıldan sonra İskandinavya'da yerini 16 işaretli Younger Futhark'a, Britanya'da ise genişletilmiş Anglo-Sakson Futhorc'a bıraktı.",
        "24 işaret, sekizerli üç gruba ayrılır. Her gruba aett (çoğulu aettir) denir; Eski İskandinavcada aile ya da soy anlamına gelir. Gruplar, başlarındaki rune'a ya da bağlı oldukları tanrıya göre anılır: Freyr ve Freyja ailesi (Fehu ile başlar), Heimdall ailesi (Hagalaz ile) ve Týr ailesi (Tiwaz ile).",
      ],
    },
    {
      title: "En eski yazıtlar",
      paragraphs: [
        "Bilinen en eski rune yazıtlarından biri, Danimarka'da bulunan ve MS 160 civarına tarihlenen Vimose tarağındaki \"harja\" kelimesidir.",
        "24 işaretin sırasıyla yazıldığı en eski eksiksiz dizi, İsveç'in Gotland adasındaki Kylver taşındadır (MS 400 civarı). Futhark'ın bugün bildiğimiz sırası büyük ölçüde bu tür dizilerden bilinir.",
      ],
    },
    {
      title: "Rune'lar ne için kullanıldı?",
      paragraphs: [
        "Rune'lar her şeyden önce bir yazıdır. Ahşap, taş, kemik ve metal eşyalara; silahlara, takılara, anıt taşlarına isimler, sahiplik işaretleri, adaklar ve kısa koruyucu formüller (alu, laukaz gibi) kazınmıştır.",
        "Romalı tarihçi Tacitus, MS 98'de yazdığı Germania'da Germen kabilelerinin meyve veren bir ağacın dalından kestikleri işaretli çubukları beyaz bir örtüye serpip kura çektiğini anlatır. Bu işaretlerin rune olup olmadığı bilinmiyor; tartışmalıdır.",
        "Arkeolojide rune'ların bugünkü gibi taş çekilerek okunduğuna dair doğrudan bir kanıt yoktur. Rune okuması büyük ölçüde modern bir yeniden kurgudur; bu uygulama da onu böyle sunar.",
      ],
    },
    {
      title: "Modern rune okuması",
      paragraphs: [
        "Rune'lara ezoterik ilgi 19. yüzyılın sonunda başladı, 20. yüzyılın ikinci yarısında bugünkü okuma pratiğine dönüştü.",
        "Bu pratiği dünyaya yayan kitap, Ralph Blum'un 1982'de yayımlanan The Book of Runes'udur. Blum, I Ching'in yapısından da esinlenerek her rune'a bir okuma anlamı verdi.",
      ],
      modern: true,
    },
    {
      title: "Boş rune",
      paragraphs: [
        "Bazı setlerde bulunan üzerinde işaret olmayan taş, Elder Futhark'ta ya da Viking Çağı buluntularında yoktur. 1982'de Ralph Blum'un kitabıyla okumaya girdi; satılan setlere yedek olarak konan boş taş, \"bilinmeyen\" anlamıyla yorumlandı.",
        "Bu uygulamada boş rune kullanılmaz.",
      ],
      modern: true,
    },
    {
      title: "Ters rune'lar",
      paragraphs: [
        "Bir rune'un ters çıktığında farklı, çoğu zaman gölgeli bir anlamla okunması da moderndir; tarot'taki ters kart okumasından uyarlanmıştır. Eski yazıtlarda böyle bir kural yoktur.",
        "Dokuz rune simetrik olduğu için ters çevrilince aynı görünür ve yalnız düz okunur: Gebo, Hagalaz, Nauthiz, Isa, Jera, Eihwaz, Sowilo, Ingwaz ve Dagaz.",
      ],
      modern: true,
    },
    {
      title: "Okumadan önce",
      paragraphs: [
        "Modern okuyucular okumaya küçük bir hazırlıkla başlar: sakin bir yer, birkaç derin nefes ve sorunun açıkça düşünülmesi. Bazıları taşları üzerine bir örtü serip çeker.",
        "Rune'lar bir kehanet değil, düşünmek için bir aynadır. Çıkan taş ne söylerse söylesin, kararın ve yolun senindir.",
      ],
      modern: true,
    },
  ],

  spreadsIntro:
    "Açılım, taşların hangi düzende çekileceği ve her yerin neyi anlatacağıdır. Bugünkü açılımların hepsi moderndir; çoğu 20. yüzyıl rune kitaplarıyla yaygınlaştı.",

  spreads: [
    {
      key: "single",
      title: "Tek Rune",
      origin: "Modern rune okumasının en sade ve en yaygın biçimi; \"günün rune'u\" da budur.",
      layout: "Kesenin içinden tek bir taş çekilir.",
      positions: ["Cevap: durumun özü, günün ana enerjisi ya da odaklanılacak nokta."],
      questions: "Günlük yön, hızlı bir netlik, \"Bugün neye dikkat etmeliyim?\" gibi sorular.",
      reading: "Tek taş bir hüküm değil, bir aynadır: günün olaylarını onun ışığında düşünürsün.",
    },
    {
      key: "three",
      title: "Geçmiş · Şimdi · Gelecek",
      origin: "Kaderi dokuyan üç Norn'dan, Urd (olan), Verdandi (olmakta olan) ve Skuld'dan (olacak) esinlenen modern bir düzen.",
      layout: "Üç taş soldan sağa yan yana dizilir.",
      positions: [
        "Geçmiş: bugünü hazırlayan etkiler ve kökler.",
        "Şimdi: şu an etkin olan durum, enerji ya da zorluk.",
        "Gelecek: yön değişmezse varılacak olası eğilim.",
      ],
      questions: "Bir sürecin nereden gelip nereye gittiğini görmek isteyen sorular.",
      reading: "Taşlar önce tek tek okunur, sonra soldan sağa bir neden-sonuç hikâyesi gibi birleştirilir.",
    },
    {
      key: "four",
      title: "4'lü İlişki Açılımı",
      origin: "İlişki sorularına göre kurulmuş modern bir düzen.",
      layout: "Dört taş yan yana dizilir.",
      positions: [
        "Senin enerjin: ilişkiye getirdiğin duygu, niyet ve bakış.",
        "Sen: ilişkideki duruşun ve beklentin.",
        "Karşı taraf: onun getirdiği his, niyet ve tutum.",
        "Sonuç: ikinizin etkileşiminden doğabilecek ortak yön.",
      ],
      questions: "İkili ilişkiler, ortaklıklar ve uyum soruları.",
      reading: "İlk iki taş seni, üçüncü taş karşı tarafı anlatır; dördüncü taş ikisinin buluştuğu yeri gösterir.",
    },
    {
      key: "five",
      title: "5'li Haç",
      origin: "Modern okuma kitaplarında geliştirilmiş bir haç düzeni.",
      layout: "Ortada bir taş, çevresinde dört taş: solda, üstte, altta ve sağda.",
      positions: [
        "Merkez: sorunun özü ve şu anki durum.",
        "Sol (geçmiş): bugüne yol açan nedenler.",
        "Üst (hedef): bilinçli amaç ya da yardım alınabilecek güç.",
        "Alt (engel): içteki direnç ya da bırakılması gereken şey.",
        "Sağ (sonuç): atılacak adım ve varılabilecek yer.",
      ],
      questions: "Karmaşık kararlar ve derinlemesine bakılması gereken durumlar.",
      reading: "Yatay çizgi zamanı (geçmiş, şimdi, sonuç), dikey çizgi iç dünyayı (engel ve hedef) anlatır; ikisinin kesiştiği merkezde okunur.",
    },
    {
      key: "scatter",
      title: "Serbest Saçılım",
      origin: "Tacitus'un anlattığı kura çekimine en yakın düşen yöntem; dokuz taş, mitolojideki dokuz dünyaya göndermedir. Uygulamada yok, bilgi için.",
      layout: "Dokuz taş kesenin içinden alınıp bir örtünün üzerine serbestçe atılır.",
      positions: [
        "Merkeze yakın düşenler: konunun acil odağı.",
        "Kenarlara düşenler: ikincil etkiler.",
        "Yüzü açık olanlar etkin durumları, kapalı olanlar henüz fark edilmeyenleri anlatır.",
      ],
      questions: "Genel bir hayat değerlendirmesi, yıllık bir bakış.",
      reading: "Taşlar birbirine yakınlıklarına göre gruplar halinde okunur.",
    },
  ],

  runes: {
    Fehu: {
      proto: "*fehu",
      poem: "Eski İngilizce şiirde servet herkese rahatlık verir; ama onur kazanmak isteyen onu cömertçe paylaşmalıdır.",
      myth: "Bolluğun tanrıları Freyr ve Freyja ile ilişkilendirilir; ilk aett onların adını taşır.",
      inner: "Tükenmişlikten sonra enerjinin toparlanması; sahip olduklarının değerini görmek.",
      shadow: "Açgözlülük; kaynağı biriktirip akışını kesmek.",
      harmony: "Uruz ile büyümeye güç katar; Hagalaz'ın fırtınasıyla sarsılabilir.",
      question: "Elimdekileri dengeli biçimde paylaşıyor muyum?",
      talisman: "Bereket ve kazanç niyetlerinde sık kullanılır.",
    },
    Uruz: {
      proto: "*ūruz",
      poem: "Şiirde yaban öküzü büyük boynuzlarıyla dövüşen, gururlu ve vahşi bir güçtür.",
      myth: "Avrupa'nın soyu tükenmiş yaban sığırı aurochs'u anlatır; modern okumalarda doğanın ham gücüyle, kimilerince Thor'la ilişkilendirilir.",
      inner: "Fiziksel ve zihinsel dayanıklılık; içindeki gücü fark etmek.",
      shadow: "Kontrolsüz öfke; gücü yanlış yere harcamak.",
      harmony: "Fehu ile dengeli büyür; Nauthiz'in kısıtlamasıyla gerilir.",
      question: "İçimdeki gücü yıkıcı değil, yapıcı bir yöne çeviriyor muyum?",
      talisman: "Dayanıklılık ve direnç niyetlerinde kullanılır.",
    },
    Thurisaz: {
      proto: "*þurisaz",
      poem: "Şiirlerde diken, ona dokunana acı veren keskin bir şeydir; dev ise yıkıcı bir güç olarak anılır.",
      myth: "Devlerle (jötnar) ve onlarla savaşan Thor'un çekici Mjölnir'le bağdaştırılır.",
      inner: "Sınırlarını korumak; ani bir uyanış.",
      shadow: "Tepkisellik; gereksiz çatışma çıkarmak.",
      harmony: "Algiz ile korumayı tamamlar; Isa'nın durgunluğuyla çelişir.",
      question: "Sınırlarımı korurken çevremi yaralayan bir dikene dönüşüyor muyum?",
      talisman: "Dışarıdan gelen tehlikelere karşı etkin koruma için çizilir.",
    },
    Ansuz: {
      proto: "*ansuz",
      poem: "Eski İngilizce şiirde dilin ve bilgeliğin kaynağıdır; İzlanda şiirinde Asgard'ın yaşlı babasıyla, Odin'le anılır.",
      myth: "Adı \"ilah\" anlamına gelir; söz, şiir ve bilgelik tanrısı Odin ile doğrudan ilişkilidir.",
      inner: "Zihinsel berraklık; söyleyeceğini bulmak.",
      shadow: "Sözü yanıltmak için kullanmak ya da yanıltılmak.",
      harmony: "Kenaz ile ilhamı büyütür; Nauthiz'in baskısında daralır.",
      question: "Sözlerim çevreme ışık mı veriyor, kafa mı karıştırıyor?",
      talisman: "İletişim, sınav ve ilham niyetlerinde kullanılır.",
    },
    Raidho: {
      proto: "*raidō",
      poem: "Şiirde salonda oturan için binicilik kolay görünür, güçlü bir atla uzun yola çıkan içinse zordur.",
      myth: "Yolculukla ve düzenli hareketle ilişkilidir; modern okumalarda hayatın ritmini anlatır.",
      inner: "Kendi ritmini bulmak; doğru zamanda yola çıkmak.",
      shadow: "Hedefsizce dolaşmak ya da bir yerde duramamak.",
      harmony: "Ehwaz ile iyi bir yol arkadaşlığı kurar; Isa ile durur.",
      question: "Hayatımın ritmi şu an benim elimde mi?",
      talisman: "Güvenli yolculuk niyetlerinde kullanılır.",
    },
    Kenaz: {
      proto: "*kaunan",
      poem: "Eski İngilizce şiirde meşale, salondakilere ışık ve sıcaklık veren parlak bir ateştir.",
      myth: "Ocak ateşiyle ve zanaatla ilişkilendirilir: ham maddeyi biçime dönüştüren kontrollü ateş.",
      inner: "İçteki ışığın uyanması; yaratma isteği.",
      shadow: "Ateşin kontrolden çıkıp yakıcı bir tutkuya dönüşmesi.",
      harmony: "Sowilo ile berraklık getirir; Laguz'un sularında sönebilir.",
      question: "Zihnimdeki ateşi bir şey üretmeye dönüştürebiliyor muyum?",
      talisman: "Yaratıcılık ve öğrenme niyetlerinde kullanılır.",
    },
    Gebo: {
      proto: "*gebō",
      poem: "Eski İngilizce şiirde cömertlik verene onur, ihtiyacı olana destek getirir.",
      myth: "Hediye alışverişinin bağ kurduğu bir dünyayı anlatır: hediye, karşılık ve bağlılık.",
      inner: "Alma ve verme arasında denge.",
      shadow: "Tek taraflı bağımlılık; verilenin karşılığını hesaplamak.",
      harmony: "Wunjo ile mutluluk getirir; Nauthiz ile bağımlılığa döner.",
      question: "İlişkilerimde alma ve verme dengesini koruyor muyum?",
      talisman: "Bağlılık ve adil ortaklık niyetlerinde kullanılır; Bağlılık Düğümü'nün temelidir.",
    },
    Wunjo: {
      proto: "*wunjō",
      poem: "Şiirde sevinç, acıyı ve kederi az bilen, bolluk ve huzur içinde yaşayanın payıdır.",
      myth: "Topluluk içindeki uyumu ve paylaşılan neşeyi anlatır.",
      inner: "İçsel doyum ve esenlik.",
      shadow: "Yüzeysel bir iyimserlikle gerçek sorunları görmezden gelmek.",
      harmony: "Gebo ile huzur kurar; Hagalaz'ın fırtınasında sarsılır.",
      question: "Bugün sevincimi kimlerle paylaşıyorum?",
      talisman: "Huzur ve paylaşılan mutluluk niyetlerinde kullanılır.",
    },
    Hagalaz: {
      proto: "*hagalaz",
      poem: "Şiirde dolu, gökten düşen en beyaz tanedir; rüzgârla savrulur, sonunda suya döner.",
      myth: "Doğanın kontrol edilemeyen güçlerini anlatır; ikinci aett onunla başlar.",
      inner: "Krizle gelen uyanış; arınma.",
      shadow: "Değişime direnip yıkımın altında kalmak.",
      harmony: "Nauthiz ile dayanıklılık kazandırır; Wunjo'nun neşesini bir süre keser.",
      question: "Hayatımdaki kaçınılmaz fırtınalardan ne öğreniyorum?",
      talisman: "Tıkanıklıkları çözme niyetlerinde kullanılır.",
    },
    Nauthiz: {
      proto: "*naudiz",
      poem: "Şiirde ihtiyaç göğsü daraltır; ama zamanında fark edilirse yardıma ve kurtuluşa dönüşür.",
      myth: "Modern okumalarda kaderi dokuyan Norn'larla ve sürtünmeyle yakılan ateşle ilişkilendirilir.",
      inner: "Öz disiplin; iradenin sınandığı zaman.",
      shadow: "Kendini çaresizliğe bırakmak.",
      harmony: "Jera ile sabırlı bir büyüme kurar; Fehu'nun bolluğuyla zıtlaşır.",
      question: "Zorluklar bana hangi gücümü öğretiyor?",
      talisman: "İrade ve dayanma gücü niyetlerinde kullanılır.",
    },
    Isa: {
      proto: "*īsaz",
      poem: "Şiirde buz çok soğuk ve kaygandır; cam gibi parlar, donmuş bir zemin olur.",
      myth: "Kışı ve durgunluğu anlatır; her şeyin hareketsiz kaldığı an.",
      inner: "Zihni dinginleştirmek; iç gözlem.",
      shadow: "Yalnızlaşmak ve duygusal olarak donmak.",
      harmony: "Jera ile buzların çözülmesini bekler; Raidho'nun hareketiyle çelişir.",
      question: "Hayatımın hangi alanında durup beklemem gerekiyor?",
      talisman: "Bir durumu sabitlemek ya da dikkati toplamak için kullanılır.",
    },
    Jera: {
      proto: "*jēra",
      poem: "Şiirde yıl ve hasat insanlara umut verir; toprak, emeğin karşılığını verir.",
      myth: "Yılın döngüsüyle ve hasatla, bolluğun tanrısı Freyr'le ilişkilendirilir.",
      inner: "Doğal ritmine uymak; emeğin meyvesini beklemek.",
      shadow: "Sabırsızlık; sonucu vaktinden önce istemek.",
      harmony: "Dagaz ile dönüşümü taçlandırır; Hagalaz ile zor bir mevsim yaşar.",
      question: "Ektiğim hangi tohumların meyvesini topluyorum?",
      talisman: "Bereket ve sabırlı büyüme niyetlerinde kullanılır.",
    },
    Eihwaz: {
      proto: "*ī(h)waz",
      poem: "Şiirde porsuk ağacının dışı serttir, kökleri derindir; ateşin bekçisidir.",
      myth: "Yüzyıllarca yaşayan porsuk, modern okumalarda dünya ağacı Yggdrasil ile, yaşamla ölüm arasındaki eşikle ilişkilendirilir.",
      inner: "Ruhsal dayanıklılık; fırtınada eğilip kırılmamak.",
      shadow: "Aşırı katılık; esnemeyi reddetmek.",
      harmony: "Perthro ile derin bir gizem kurar; Hagalaz'ın fırtınasına göğüs gerer.",
      question: "Fırtınalar karşısında eğilip ayakta kalabiliyor muyum?",
      talisman: "Sarsılmaz koruma niyetlerinde kullanılır.",
    },
    Perthro: {
      proto: "*perþō",
      poem: "Eski İngilizce şiirde savaşçıların salonda oynayıp güldüğü bir oyundur.",
      myth: "Anlamı tam bilinmeyen tek rune'dur; çoğu yorum onu zar kupasıyla, şansla ve kaderin gizemiyle bağdaştırır.",
      inner: "Sezgiyi dinlemek; gizli olanı sezmek.",
      shadow: "Her şeyi şansa bırakıp sorumluluktan kaçmak.",
      harmony: "Eihwaz ile kaderin derinliğini anlatır; Ansuz'un çarpıtılmış sözüyle çatışır.",
      question: "Hayatın bana getireceği sürprizlere ne kadar açığım?",
      talisman: "Şans ve sezgi niyetlerinde kullanılır.",
    },
    Algiz: {
      proto: "*algiz",
      poem: "Eski İngilizce şiirde bataklıkta biten ve ona dokunan eli kesen bir sazdır.",
      myth: "Adı sığın (elk) ile ilişkilendirilir; yukarı açılan kolları koruyucu bir kalkan gibi okunur.",
      inner: "Sezgisel uyanıklık; kendini güvende hissetmek.",
      shadow: "Her yerde tehlike görüp hep tetikte yaşamak.",
      harmony: "Sowilo ile güçlü bir zırh olur; Thurisaz'ın kontrolsüzlüğüyle zıtlaşır.",
      question: "Kendi sınırlarımı koruyabiliyor muyum?",
      talisman: "En yaygın koruma işaretidir; koruma tılsımlarının çoğunda yer alır.",
    },
    Sowilo: {
      proto: "*sōwilō",
      poem: "Şiirde güneş denizcilere yol gösterir, karadakilere sevinç ve ışık verir.",
      myth: "Güneşin kendisidir; İskandinav anlatılarında güneşi gökte taşıyan Sól ile ilişkilendirilir.",
      inner: "Canlılık; bütünleşme ve kendine güven.",
      shadow: "Aşırı ego; çevresini yakıp kavurmak.",
      harmony: "Tiwaz ile zafere ulaştırır; Isa'nın buzunu eritir.",
      question: "Işığımla çevreme sıcaklık katıyor muyum?",
      talisman: "Başarı ve enerji niyetlerinde kullanılır.",
    },
    Tiwaz: {
      proto: "*tīwaz",
      poem: "Eski İngilizce şiirde gece sisinin üstünde yolunu şaşırmayan, sözünü tutan bir yol gösterici yıldızdır.",
      myth: "Adalet ve fedakârlık tanrısı Týr ile doğrudan ilişkilidir; üçüncü aett onun adını taşır.",
      inner: "Sarsılmaz irade; doğru bildiğinin arkasında durmak.",
      shadow: "Katı kuralcılık; körü körüne bağlılık.",
      harmony: "Berkano ile dengeli bir güç kurar; çarpıtılmış söze tahammül etmez.",
      question: "İnandığım değerler için adilce mücadele ediyor muyum?",
      talisman: "Cesaret, adalet ve zafer niyetlerinde kullanılır.",
    },
    Berkano: {
      proto: "*berkanan",
      poem: "Eski İngilizce şiirde huş ağacı, tohumsuz olsa da sürgün verir; dalları güzeldir, yaprakları göğe uzanır.",
      myth: "Doğumla, büyümeyle ve koruyucu bir anneliğe dair imgelerle ilişkilendirilir.",
      inner: "Yenilenme; kendini şefkatle beslemek.",
      shadow: "Aşırı korumacılıkla karşısındakini boğmak.",
      harmony: "Tiwaz ile dengeli büyür; Hagalaz ile zor bir dönem yaşar.",
      question: "Taze bir başlangıç için neyi beslemem gerekiyor?",
      talisman: "Yeni başlangıç, aile ve yenilenme niyetlerinde kullanılır.",
    },
    Ehwaz: {
      proto: "*ehwaz",
      poem: "Şiirde at, binicisine gurur ve sevinç verir; huzursuz olana bir avuntudur.",
      myth: "At ile binicisi arasındaki güveni anlatır: iki varlığın birlikte yol alması.",
      inner: "Beden ile zihnin uyumu.",
      shadow: "Körü körüne güvenip kendi yönünü kaybetmek.",
      harmony: "Mannaz ile toplulukta uyum kurar; Nauthiz ile güvensizliğe düşer.",
      question: "İlişkilerimde ne kadar güven uyandırıyorum?",
      talisman: "Karşılıklı güven ve iş birliği niyetlerinde kullanılır.",
    },
    Mannaz: {
      proto: "*mannaz",
      poem: "Eski İngilizce şiirde insan yakınları için değerlidir; ama her insan bir gün toprağa döner.",
      myth: "İnsanı, insan topluluğunu ve kişinin kendini tanımasını anlatır.",
      inner: "Kendi benliğini tanımak; insan olmanın sınırlarını kabul etmek.",
      shadow: "Kalabalığın içinde kendini kaybetmek.",
      harmony: "Ehwaz ile uyum kurar; Hagalaz'ın krizinde yalnızlaşabilir.",
      question: "Toplum içindeki rolüm kendi özüme ne kadar uygun?",
      talisman: "Topluluk desteği ve öz farkındalık niyetlerinde kullanılır.",
    },
    Laguz: {
      proto: "*laguz",
      poem: "Eski İngilizce şiirde su, sallanan bir gemiyle denize açılanlara sonsuz görünür; dalgalar onları korkutur.",
      myth: "Suyu, akışı ve derinliği anlatır; modern okumalarda bilinçaltıyla ve duygularla ilişkilendirilir.",
      inner: "Sezgilere güvenmek; akışa bırakmak.",
      shadow: "Duygularda boğulup aklını kaybetmek.",
      harmony: "Ingwaz ile içten olgunlaşır; Kenaz'ın ateşini söndürebilir.",
      question: "Sezgilerimin sesini dinliyor muyum?",
      talisman: "Sezgi ve rüya niyetlerinde kullanılır.",
    },
    Ingwaz: {
      proto: "*ingwaz",
      poem: "Eski İngilizce şiirde Ing önce Doğu Danlar arasında görülür, sonra arabasıyla dalgaların ötesine gider.",
      myth: "Bereketin tanrısı Ing'in (Freyr'in bir adı sayılır) rune'udur; tohumun içindeki saklı gücü anlatır.",
      inner: "Enerjiyi içte biriktirmek; olgunlaşmayı beklemek.",
      shadow: "Tohumu hep içte tutup hiç ekmemek.",
      harmony: "Berkano ile yeni doğuşlar getirir; Isa'nın beklemesinde sabırlıdır.",
      question: "İçimde olgunlaşmayı bekleyen ne var?",
      talisman: "Tamamlanma ve yeni başlangıç niyetlerinde kullanılır.",
    },
    Dagaz: {
      proto: "*dagaz",
      poem: "Eski İngilizce şiirde gün, herkese değerli bir ışık; zengine de yoksula da umut ve sevinçtir.",
      myth: "Gecenin günle birleştiği şafak anını anlatır: karanlıktan aydınlığa geçiş.",
      inner: "Zihindeki karanlığın dağılması; berraklık.",
      shadow: "Değişimin hızına yetişemeyip gözü kamaşmak.",
      harmony: "Sowilo ile tam bir aydınlık getirir; Isa'nın donukluğuyla zıtlaşır.",
      question: "Hayatımda hangi karanlık alanın aydınlanmasına izin veriyorum?",
      talisman: "Uyanış ve yeni sayfa niyetlerinde kullanılır.",
    },
    Othala: {
      proto: "*ōþala",
      poem: "Eski İngilizce şiirde ata toprağı, insanın evinde huzur ve bolluk içinde yaşayabildiği sürece değerlidir.",
      myth: "Miras kalan toprağı, atalardan gelenleri ve aidiyeti anlatır.",
      inner: "Köklerine sahip çıkmak; bir yere ait olmak.",
      shadow: "Geçmişin gölgesinde yaşamak; değişime kapanmak.",
      harmony: "Fehu ile kalıcı bir refah kurar; Hagalaz ile köklerinden sınanabilir.",
      question: "Atalarımdan gelen hangi değer beni bugün ayakta tutuyor?",
      talisman: "Ev, aile ve mülk niyetlerinde kullanılır.",
    },
  },
};
